#!/usr/bin/env bash
set -euo pipefail

PROFILE="core"
DRY_RUN=0
CHECK_ONLY=0
INIT_BASELINE_CONFIG=0
TARGET_DIR="."

usage() {
  cat <<'EOF'
Usage: ./install-scanners.sh [options]

Install scanner prerequisites used by CodeGauge.

Options:
  --profile <name>   Install profile (default: core)
                     Profiles: core, python, javascript, go, php, security, infra, java, all
  --dry-run          Print commands without executing
  --check            Only report whether required binaries are on PATH
  --init-config      Write baseline scanner config files if missing
  --target-dir <dir> Target directory for --init-config (default: current dir)
  -h, --help         Show this help

Examples:
  ./install-scanners.sh --profile core
  ./install-scanners.sh --profile python
  ./install-scanners.sh --profile all --dry-run
  ./install-scanners.sh --profile security --check
  ./install-scanners.sh --init-config --target-dir /path/to/project
EOF
}

has() {
  command -v "$1" >/dev/null 2>&1
}

run_cmd() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] %s\n' "$*"
    return 0
  fi
  printf '[run] %s\n' "$*"
  "$@"
}

check_bin() {
  local bin="$1"
  if has "$bin"; then
    printf '[ok] %s\n' "$bin"
  else
    printf '[missing] %s\n' "$bin"
  fi
}

write_if_missing() {
  local path="$1"
  local content="$2"
  if [[ -e "$path" ]]; then
    printf '[skip] exists: %s\n' "$path"
    return 0
  fi
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] create %s\n' "$path"
    return 0
  fi
  printf '%s' "$content" >"$path"
  printf '[created] %s\n' "$path"
}

init_baseline_config() {
  local root="$1"
  if [[ ! -d "$root" ]]; then
    printf '[error] target directory does not exist: %s\n' "$root" >&2
    exit 2
  fi

  local codegauge_toml="$root/.codegauge.toml"
  local ruff_toml="$root/.ruff.toml"
  local pyright_json="$root/pyrightconfig.json"
  local bandit_cfg="$root/.bandit"
  local eslint_ignore="$root/.eslintignore"
  local coveragerc="$root/.coveragerc"

  write_if_missing "$codegauge_toml" '# Baseline CodeGauge config generated by install-scanners.sh
default_timeout_seconds = 90

exclude = [
  ".venv/**",
  "venv/**",
  ".git/**",
  ".pytest_cache/**",
  ".ruff_cache/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  ".next/**",
  ".nuxt/**",
  "coverage/**",
]

enabled_scanners = ["ruff", "pyright", "radon", "bandit"]
disabled_scanners = []
'

  write_if_missing "$ruff_toml" '# Baseline Ruff config generated by install-scanners.sh
exclude = [
  ".git",
  ".venv",
  "venv",
  "node_modules",
  "dist",
  "build",
  "coverage",
]
'

  write_if_missing "$pyright_json" '{
  "$schema": "https://raw.githubusercontent.com/microsoft/pyright/main/packages/vscode-pyright/schemas/pyrightconfig.schema.json",
  "venvPath": ".",
  "venv": ".venv",
  "exclude": [
    "**/.git",
    "**/.venv",
    "**/venv",
    "**/node_modules",
    "**/dist",
    "**/build",
    "**/.pytest_cache",
    "**/.ruff_cache"
  ]
}
'

  write_if_missing "$bandit_cfg" '# Baseline Bandit config generated by install-scanners.sh
[bandit]
exclude_dirs = tests,.venv,venv,node_modules,dist,build
skips = B101
'

  write_if_missing "$eslint_ignore" '# Baseline ESLint ignore file generated by install-scanners.sh
.git/
.venv/
venv/
node_modules/
dist/
build/
coverage/
'

  write_if_missing "$coveragerc" '# Baseline coverage config generated by install-scanners.sh
[run]
omit =
    */.venv/*
    */venv/*
    */node_modules/*
    */dist/*
    */build/*
    */tests/*
'
}

install_python() {
  if ! has uv; then
    printf '[skip] uv not found; cannot install Python scanner tools\n'
    return 0
  fi
  run_cmd uv tool install ruff
  run_cmd uv tool install bandit
  run_cmd uv tool install radon
  run_cmd uv tool install vulture
  run_cmd uv tool install pyright
  run_cmd uv tool install coverage
}

install_javascript() {
  if ! has npm; then
    printf '[skip] npm not found; cannot install JavaScript/TypeScript scanner tools\n'
    return 0
  fi
  run_cmd npm install -g eslint typescript
}

install_go() {
  if ! has go; then
    printf '[skip] go not found; cannot install Go scanner tools\n'
    return 0
  fi
  run_cmd go install honnef.co/go/tools/cmd/staticcheck@latest
  run_cmd go install golang.org/x/vuln/cmd/govulncheck@latest
}

install_php() {
  if ! has composer; then
    printf '[skip] composer not found; cannot install PHP scanner tools\n'
    return 0
  fi
  run_cmd composer global require phpstan/phpstan
  run_cmd composer global require squizlabs/php_codesniffer
}

install_security() {
  if has brew; then
    run_cmd brew install gitleaks
    run_cmd brew install trufflehog
    run_cmd brew install shellcheck
  else
    printf '[info] Homebrew not found; install manually: gitleaks, trufflehog, shellcheck\n'
  fi
  printf '[info] Install opengrep manually for your platform and ensure it is on PATH\n'
}

install_infra() {
  if has brew; then
    run_cmd brew install shellcheck
  else
    printf '[info] Homebrew not found; install shellcheck manually\n'
  fi
  printf '[info] Install opengrep manually for your platform and ensure it is on PATH\n'
}

check_python() {
  check_bin ruff
  check_bin bandit
  check_bin radon
  check_bin vulture
  check_bin pyright
  check_bin coverage
}

check_javascript() {
  check_bin eslint
  check_bin tsc
  check_bin npm
  check_bin node
}

check_go() {
  check_bin go
  check_bin staticcheck
  check_bin govulncheck
}

check_php() {
  check_bin composer
  check_bin phpstan
  check_bin phpcs
}

check_security() {
  check_bin gitleaks
  check_bin trufflehog
  check_bin opengrep
  check_bin shellcheck
  check_bin git
}

check_java() {
  check_bin java
  check_bin javac
  if has mvn || has gradle || [[ -x "./gradlew" ]]; then
    printf '[ok] Java build runner present (mvn/gradle/gradlew)\n'
  else
    printf '[missing] Java build runner (mvn/gradle/gradlew)\n'
  fi
}

run_profile_install() {
  case "$1" in
    core)
      install_python
      ;;
    python)
      install_python
      ;;
    javascript)
      install_javascript
      ;;
    go)
      install_go
      ;;
    php)
      install_php
      ;;
    security)
      install_security
      ;;
    infra)
      install_infra
      ;;
    java)
      printf '[info] Java scanners rely on project plugins and build runner; no global install step performed\n'
      ;;
    all)
      install_python
      install_javascript
      install_go
      install_php
      install_security
      install_infra
      ;;
    *)
      printf 'Unknown profile: %s\n' "$1" >&2
      exit 2
      ;;
  esac
}

run_profile_check() {
  case "$1" in
    core)
      check_python
      ;;
    python)
      check_python
      ;;
    javascript)
      check_javascript
      ;;
    go)
      check_go
      ;;
    php)
      check_php
      ;;
    security)
      check_security
      ;;
    infra)
      check_bin shellcheck
      check_bin opengrep
      ;;
    java)
      check_java
      ;;
    all)
      check_python
      check_javascript
      check_go
      check_php
      check_security
      check_java
      ;;
    *)
      printf 'Unknown profile: %s\n' "$1" >&2
      exit 2
      ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="${2:-}"
      if [[ -z "$PROFILE" ]]; then
        printf '--profile requires a value\n' >&2
        exit 2
      fi
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    --init-config)
      INIT_BASELINE_CONFIG=1
      shift
      ;;
    --target-dir)
      TARGET_DIR="${2:-}"
      if [[ -z "$TARGET_DIR" ]]; then
        printf '--target-dir requires a value\n' >&2
        exit 2
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$CHECK_ONLY" -eq 1 ]]; then
  run_profile_check "$PROFILE"
else
  run_profile_install "$PROFILE"
  printf '\n'
  printf 'Availability check after install:\n'
  run_profile_check "$PROFILE"
fi

if [[ "$INIT_BASELINE_CONFIG" -eq 1 ]]; then
  printf '\n'
  printf 'Writing baseline scanner config files (if missing):\n'
  init_baseline_config "$TARGET_DIR"
fi
